web/bitstream/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lyrics.urls')),
    path('lyrics/', include('lyrics.urls')),
    path('weekly_chart/', include('weekly_chart.urls')),  
    path('season/', include('season.urls')),
    path('hitmakers/', include("hitmakers.urls")),
    
]

web/lyrics/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='lyrics_index'),
    path('wordcloud/', views.wordcloud_view, name='wordcloud'),
    path('analysis/', views.analysis_view, name='analysis'),
]

web/season/urls.py
from django.urls import path
from . import views
from .views import SpringView, SummerView, FallView, WinterView

app_name = 'season'
urlpatterns =[
    path('', views.index, name = 'season_index'),
    path('spring/', SpringView.as_view(), name = 'season_spring'),
    path('summer/', SummerView.as_view(), name = 'season_summer'),
    path('fall/', FallView.as_view(), name = 'season_fall'),
    path('winter/', WinterView.as_view(), name = 'season_winter'),
]

web/season/models.py
from django.db import models

# Create your models here.
class GenreCount(models.Model):
    genre = models.CharField(max_length = 20)
    genre_count = models.IntegerField()
    season = models.CharField(max_length = 10)

    def __str__(self):
        return f'genre : {self.genre} genre_count : {self.genre_count} season : {self.season}'

class TopSongs(models.Model):
    genre = models.CharField(max_length = 100)
    song_name = models.CharField(max_length = 100)
    chart_count = models.IntegerField()
    season = models.CharField(max_length = 10)

    def __str__(self):
        return f'genre : {self.genre} song_name : {self.song_name} chart_count : {self.chart_count} season : {self.season}'

class SongImage(models.Model):
    song_name = models.CharField(max_length = 100)
    album_url = models.CharField(max_length = 200)

    def __str__(self):
        return f'song_name : {self.song_name} album_url : {self.album_url}'

web/season/views.py
from django.shortcuts import render
from django.views import generic
from django.http import JsonResponse
from season.data_processor import get_pie_chart, get_bar_chart

# Create your views here.
def index(request):
    return render(request, 'season/season_index.html')


class BaseSeasonView(generic.TemplateView):
    """
    계절별 뷰의 공통 로직을 담은 기본 클래스
    중복 코드를 제거하고 유지보수성을 향상
    """
    season = None  # 하위 클래스에서 반드시 정의해야 함
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Pie Chart 데이터 가져오기
        top5_genre, top5_genre_count, top5_selector = get_pie_chart(self.season)
        context['top5_genre'] = top5_genre
        context['top5_genre_count'] = top5_genre_count
        context['top5_selector'] = top5_selector
        
        # 초기 장르 설정 (기본값: '댄스')
        default_genre = '댄스'
        top3_song_names, top3_song_counts, top3_song_images = get_bar_chart(
            self.season, 
            default_genre
        )
        context['top3_songs'] = list(zip(top3_song_names, top3_song_counts, top3_song_images))
        context['selected_genre'] = default_genre
        
        return context
    
    def render_to_response(self, context, **response_kwargs):
        """AJAX 요청 처리"""
        if self.request.GET.get('ajax') == '1':
            selected_genre = self.request.GET.get('genre', '댄스')
            top3_song_names, top3_song_counts, top3_song_images = get_bar_chart(
                self.season, 
                selected_genre
            )
            context['top3_songs'] = list(zip(top3_song_names, top3_song_counts, top3_song_images))
            context['selected_genre'] = selected_genre
            
            return JsonResponse({'top3_songs': context['top3_songs']})
        
        return super().render_to_response(context, **response_kwargs)


class SpringView(BaseSeasonView):
    """봄 시즌 뷰"""
    template_name = 'season/season_spring.html'
    season = 'spring'


class SummerView(BaseSeasonView):
    """여름 시즌 뷰"""
    template_name = 'season/season_summer.html'
    season = 'summer'


class FallView(BaseSeasonView):
    """가을 시즌 뷰"""
    template_name = 'season/season_fall.html'
    season = 'fall'


class WinterView(BaseSeasonView):
    """겨울 시즌 뷰"""
    template_name = 'season/season_winter.html'
    season = 'winter'

web/season/templates/season/season_fall.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'season/css/season_style.css' %}">

    <div class = 'single_section'>
        <div class = 'section_title'>최근 5년간 가을 차트에 가장 많이 등장하는 장르 TOP 5</div>
        <div class = 'main_pie_chart'>
            <canvas id = "top5GenrePie"></canvas>
        </div>
    </div>

    <div class = 'single_section'>
        <div class = 'section_title_long'>장르별 차트 진입 횟수 TOP 3 노래</div>
        <div class = 'double_section'>
            <div class = 'section_left'>
                <a id = 'album_title'>{{ selected_genre }} TOP 3</a>

                <div class="top3_song">
                    {% for name, count, img_url in top3_songs %}
                    <div class="top_song">
                        <a class="rank">{{ forloop.counter }}</a>
                        <img src="{{ img_url }}" width="150" height="150" alt="{{ forloop.counter }}"> 
                        <a class='song_name'>{{ name }}</a>
                        <a class='song_count'>차트 진입 : {{ count }}회</a>
                    </div>
                    {% endfor %}
                </div>

                <select id = 'select_genre'>
                    {% for genre in top5_selector %}
                    <option value = '{{ genre }}'
                            {% if genre == selected_genre %}
                            selected
                            {% endif %}>
                            {{ genre }}
                    </option>
                    {% endfor %}
                </select>
            </div>
            
            <div class = 'section_right'>
                <canvas id = "top3SongBarChart"></canvas>
            </div>
        </div>
    </div>
    
    <div class = 'single_section'>
        <div class = section_title>다른 계절 보기</div>
        <div class = 'list_wrapper'>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_spring" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/10129/10129544.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>봄</span>
                </dd>
            </dl>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_summer" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/2664/2664593.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>여름</span>
                </dd>
            </dl>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_winter" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/667/667664.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>겨울</span>
                </dd>
            </dl>
        </div>
    </div>

    {{ top5_genre|json_script:"top5Genre" }}
    {{ top5_genre_count|json_script:"top5GenreCount" }}
    {{ top3_songs|json_script:"top3Song" }}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src = "{% static 'season/js/pie_chart.js' %}"></script>
    <script src = "{% static 'season/js/genre_chart.js' %}"></script>
{% endblock %}

web/season/templates/season/season_index.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'season/css/season_index_style.css' %}">
<div class = 'season_title'>
    <h2>계절별 유행 분석</h2>
    <p class = 'description'>(2020.09 ~ 2025.08)기간의 멜론 월간차트의 데이터를 이용하였습니다.</p>
</div>
<div class = 'list_wrapper'>
    <dl class = 'season_list'>
        <dd>
            <a class = 'season_image' href = '{% url "season:season_spring" %}'>
                <img src = 'https://cdn-icons-png.flaticon.com/128/10129/10129544.png' width = 200, height = 200>
            </a>
        </dd>
        <dd>
            <span class = 'season_name'>봄</span>
        </dd>
    </dl>
    <dl class = 'season_list'>
        <dd>
            <a class = 'season_image' href = '{% url "season:season_summer" %}'>
                <img src = 'https://cdn-icons-png.flaticon.com/128/2664/2664593.png' width = 200, height = 200>
            </a>
        </dd>
        <dd>
            <span class = 'season_name'>여름</span>
        </dd>
    </dl>
    <dl class = 'season_list'>
        <dd>
            <a class = 'season_image' href = '{% url "season:season_fall" %}'>
                <img src = 'https://cdn-icons-png.flaticon.com/128/2146/2146386.png' width = 200, height = 200>
            </a>
        </dd>
        <dd>
            <span class = 'season_name'>가을</span>
        </dd>
    </dl>
    <dl class = 'season_list'>
        <dd>
            <a class = 'season_image' href = '{% url "season:season_winter" %}'>
                <img src = 'https://cdn-icons-png.flaticon.com/128/667/667664.png' width = 200, height = 200>
            </a>
        </dd>
        <dd>
            <span class = 'season_name'>겨울</span>
        </dd>
    </dl>
</div>
{% endblock %}

web/season/templates/season/season_spring.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'season/css/season_style.css' %}">

    <div class = 'single_section'>
        <div class = 'section_title'>최근 5년간 봄 차트에 가장 많이 등장하는 장르 TOP 5</div>
        <div class = 'main_pie_chart'>
            <canvas id = "top5GenrePie"></canvas>
        </div>
    </div>

    <div class = 'single_section'>
        <div class = 'section_title_long'>장르별 차트 진입 횟수 TOP 3 노래</div>
        <div class = 'double_section'>
            <div class = 'section_left'>
                <a id = 'album_title'>{{ selected_genre }} TOP 3</a>

                <div class="top3_song">
                    {% for name, count, img_url in top3_songs %}
                    <div class="top_song">
                        <a class="rank">{{ forloop.counter }}</a>
                        <img src="{{ img_url }}" width="150" height="150" alt="{{ forloop.counter }}"> 
                        <a class='song_name'>{{ name }}</a>
                        <a class='song_count'>차트 진입 : {{ count }}회</a>
                    </div>
                    {% endfor %}
                </div>

                <select id = 'select_genre'>
                    {% for genre in top5_selector %}
                    <option value = '{{ genre }}'
                            {% if genre == selected_genre %}
                            selected
                            {% endif %}>
                            {{ genre }}
                    </option>
                    {% endfor %}
                </select>
            </div>
            
            <div class = 'section_right'>
                <canvas id = "top3SongBarChart"></canvas>
            </div>
        </div>
    </div>

    <div class = 'single_section'>
        <div class = 'section_title'>다른 계절 보기</div>
        <div class = 'list_wrapper'>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_summer" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/2664/2664593.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>여름</span>
                </dd>
            </dl>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_fall" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/2146/2146386.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>가을</span>
                </dd>
            </dl>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_winter" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/667/667664.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>겨울</span>
                </dd>
            </dl>
        </div>
    </div>

    {{ top5_genre|json_script:"top5Genre" }}
    {{ top5_genre_count|json_script:"top5GenreCount" }}
    {{ top3_songs|json_script:"top3Song" }}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src = "{% static 'season/js/pie_chart.js' %}"></script>
    <script src = "{% static 'season/js/genre_chart.js' %}"></script>
{% endblock %}

web/season/templates/season/season_summer.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'season/css/season_style.css' %}">

    <div class = 'single_section'>
        <div class = 'section_title'>최근 5년간 여름 차트에 가장 많이 등장하는 장르 TOP 5</div>
        <div class = 'main_pie_chart'>
            <canvas id = "top5GenrePie"></canvas>
        </div>
    </div>

    <div class = 'single_section'>
        <div class = 'section_title_long'>장르별 차트 진입 횟수 TOP 3 노래</div>
        <div class = 'double_section'>
            <div class = 'section_left'>
                <a id = 'album_title'>{{ selected_genre }} TOP 3</a>

                <div class="top3_song">
                    {% for name, count, img_url in top3_songs %}
                    <div class="top_song">
                        <a class="rank">{{ forloop.counter }}</a>
                        <img src="{{ img_url }}" width="150" height="150" alt="{{ forloop.counter }}"> 
                        <a class='song_name'>{{ name }}</a>
                        <a class='song_count'>차트 진입 : {{ count }}회</a>
                    </div>
                    {% endfor %}
                </div>

                <select id = 'select_genre'>
                    {% for genre in top5_selector %}
                    <option value = '{{ genre }}'
                            {% if genre == selected_genre %}
                            selected
                            {% endif %}>
                            {{ genre }}
                    </option>
                    {% endfor %}
                </select>
            </div>
            
            <div class = 'section_right'>
                <canvas id = "top3SongBarChart"></canvas>
            </div>
        </div>
    </div>

    <div class = 'single_section'>
        <div class = section_title>다른 계절 보기</div>
        <div class = 'list_wrapper'>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_spring" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/10129/10129544.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>봄</span>
                </dd>
            </dl>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_fall" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/2146/2146386.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>가을</span>
                </dd>  
            </dl>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_winter" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/667/667664.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>겨울</span>
                </dd>
            </dl>
        </div>
    </div>

    {{ top5_genre|json_script:"top5Genre" }}
    {{ top5_genre_count|json_script:"top5GenreCount" }}
    {{ top3_songs|json_script:"top3Song" }}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src = "{% static 'season/js/pie_chart.js' %}"></script>
    <script src = "{% static 'season/js/genre_chart.js' %}"></script>
{% endblock %}

web/season/templates/season/season_winter.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'season/css/season_style.css' %}">

    <div class = 'single_section'>
        <div class = 'section_title'>최근 5년간 겨울 차트에 가장 많이 등장하는 장르 TOP 5</div>
        <div class = 'main_pie_chart'>
            <canvas id = "top5GenrePie"></canvas>
        </div>
    </div>

    <div class = 'single_section'>
        <div class = 'section_title_long'>장르별 차트 진입 횟수 TOP 3 노래</div>
        <div class = 'double_section'>
            <div class = 'section_left'>
                <a id = 'album_title'>{{ selected_genre }} TOP 3</a>

                <div class="top3_song">
                    {% for name, count, img_url in top3_songs %}
                    <div class="top_song">
                        <a class="rank">{{ forloop.counter }}</a>
                        <img src="{{ img_url }}" width="150" height="150" alt="{{ forloop.counter }}"> 
                        <a class='song_name'>{{ name }}</a>
                        <a class='song_count'>차트 진입 : {{ count }}회</a>
                    </div>
                    {% endfor %}
                </div>

                <select id = 'select_genre'>
                    {% for genre in top5_selector %}
                    <option value = '{{ genre }}'
                            {% if genre == selected_genre %}
                            selected
                            {% endif %}>
                            {{ genre }}
                    </option>
                    {% endfor %}
                </select>
            </div>
            
            <div class = 'section_right'>
                <canvas id = "top3SongBarChart"></canvas>
            </div>
        </div>
    </div>

    <div class = 'single_section'>
        <div class = section_title>다른 계절 보기</div>
        <div class = 'list_wrapper'>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_spring" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/10129/10129544.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>봄</span>
                </dd>
            </dl>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_summer" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/2664/2664593.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>여름</span>
                </dd>
            </dl>
            <dl class = 'season_list'>
                <dd>
                    <a class = 'season_image' href = '{% url "season:season_fall" %}'>
                        <img src = 'https://cdn-icons-png.flaticon.com/128/2146/2146386.png' width = 150, height = 150>
                    </a>
                </dd>
                <dd>
                    <span class = 'season_name'>가을</span>
                </dd>
            </dl>
        </div>
    </div>

    {{ top5_genre|json_script:"top5Genre" }}
    {{ top5_genre_count|json_script:"top5GenreCount" }}
    {{ top3_songs|json_script:"top3Song" }}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src = "{% static 'season/js/pie_chart.js' %}"></script>
    <script src = "{% static 'season/js/genre_chart.js' %}"></script>
{% endblock %}